### ISSUE TITLE
Adapter crash after start

### ISSUE THREAD

**Issue by schmupu** [iobroker-community-adapters/ioBroker.statistics#37]
The adapter crash every few seconds.  I hope you can help

Statistics Version: 0.2.2
js-controller: 2.2.9
Node.js: v10.18.1
NPM: 6.13.4

```
2020-02-22 15:05:05.965  - error: host.iobroker Caught by controller[0]: TypeError: groups[g].indexOf is not a function
2020-02-22 15:05:05.966  - error: host.iobroker Caught by controller[0]:     at removeObject (/opt/iobroker/node_modules/iobroker.statistics/main.js:190:70)
2020-02-22 15:05:05.967  - error: host.iobroker Caught by controller[0]:     at Object.objectChange (/opt/iobroker/node_modules/iobroker.statistics/main.js:99:21)
2020-02-22 15:05:05.968  - error: host.iobroker Caught by controller[0]:     at Immediate.options.objectChange.function.setImmediate (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:1506:94)
2020-02-22 15:05:05.968  - error: host.iobroker Caught by controller[0]:     at runCallback (timers.js:705:18)
2020-02-22 15:05:05.968  - error: host.iobroker Caught by controller[0]:     at tryOnImmediate (timers.js:676:5)
2020-02-22 15:05:05.969  - error: host.iobroker Caught by controller[0]:     at processImmediate (timers.js:658:5)
```

**Comment by foxthefox** [comment]
I hope, what was the action you did before of this crashing?
Did you add new data point or did you activate something additionally for statistics?
